name: Salah Sync Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Secret is present
        run: |
          if [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "Error: CRON_SECRET is not set in GitHub repository secrets."
            exit 1
          else
            echo "Success: CRON_SECRET is set."
          fi

      - name: Call Vercel Cron API
        run: |
          curl --fail -X GET -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" "https://salah-sync-six.vercel.app/api/cron"
