name: Salah Sync Cron Job

#on:
  #schedule:
    # Runs every 5 minutes
 #   - cron: "*/5 * * * *"
  #workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      # This securely maps your GitHub secret to an environment variable
      # that the 'run' step can use. This is the safest way.
      CRON_SECRET_FROM_ENV: ${{ secrets.CRON_SECRET }}

    steps:
      - name: Call Vercel Cron API
        run: |
          # The shell will now correctly use the environment variable,
          # regardless of any special characters it contains.
          curl --fail -X GET \
          -H "Authorization: Bearer $CRON_SECRET_FROM_ENV" \
          "https://salah-sync-six.vercel.app/api/cron"
